# DataFrame과 리스트 딕셔너리 ndarraty 상호 변환

### 1. 1차원 데이터를 DataFrame으로 변환

In [15]:
import warnings
warnings.filterwarnings(action='ignore')

import pandas as pd
import numpy as np

In [16]:
# 1차원 리스트 생성
col_name1 = ['col1']
list1 = [1,2,3]
print(list1, type(list1))

[1, 2, 3] <class 'list'>

In [17]:
# ndarray로 변환
arr1= np.array(list1)
print(arr1, type(arr1))

[1 2 3] <class 'numpy.ndarray'>

In [25]:
# list1, arr1을 DataFrame으로 생성
df1_1 = pd.DataFrame(list1, columns=col_name1, index=['a', 'b', 'c'])
df1_2 = pd.DataFrame(arr1, columns=col_name1)

In [26]:
print(df1_1)
print(df1_2)

   col1
a     1
b     2
c     3
   col1
0     1
1     2
2     3

### 2. 2차원 데이터를 DataFrame으로 변환

In [27]:
# 컬럼명 생성
col_names = ['col1', 'col2', 'col3']
col_names

['col1', 'col2', 'col3']

In [29]:
# 2차원 리스트 생성
list2 = [[1,2,3], [4,5,6]]
list2

[[1, 2, 3], [4, 5, 6]]

In [31]:
#mdarray로 변환
arr2 = np.array(list2)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
# list2, arr2를 DataFrame으로 변환
df2_1 = pd.DataFrame(list2, columns = col_names)
df2_2 = pd.DataFrame(arr2, columns = col_names)

In [36]:
print(df2_1)
print(df2_2)

   col1  col2  col3
0     1     2     3
1     4     5     6
   col1  col2  col3
0     1     2     3
1     4     5     6

### 3. 딕셔너리를 DataFrame으로 변환

In [37]:
# 딕셔너리 생성
dict1 = {
    'col1': [1,2,3],
    'col2': [4,5,6],
    'col3': [7,8,9]
}
dict1

{'col1': [1, 2, 3], 'col2': [4, 5, 6], 'col3': [7, 8, 9]}

In [39]:
df_dict1 = pd.DataFrame(dict1)
df_dict1
# 시리즈가 여러개 묶인 것 = DataFrame

   col1  col2  col3
0     1     4     7
1     2     5     8
2     3     6     9

### 4. DataFrame을 ndarray, list, dictionary로 변환

In [44]:
# df_dict1 데이터프레임을 ndarray로 변환
# arr_dict1 = np.array(df_dict1)
arr_dict1 = df_dict1.values
arr_dict1

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [47]:
# df_dict1 데이터프레임을 list로 변환
list3 = df_dict1.values.tolist() # values까지는 array로 변환
list3

[[1, 4, 7], [2, 5, 8], [3, 6, 9]]

In [50]:
# df_dict1 데이터프레임을 dictionary로 변환
dict3 = df_dict1.to_dict()
dict3

{'col1': {0: 1, 1: 2, 2: 3},
 'col2': {0: 4, 1: 5, 2: 6},
 'col3': {0: 7, 1: 8, 2: 9}}

### 5. shape 속성 정리
- python: List : ❌ AttributeError
- python: Dictionary  : ❌ AttributeError
- python: Ndarray : 🅾️ 사용가능
- pandas: DataGFrame : 🅾️ 사용가능
- pandasL Series : 🅾️ 사용가능

In [ ]:
# list 생성
list1
print(list1.shape) # ❌ AttributeError: type object 'list' has no attribute 'shape'

In [ ]:
# dict 생성
dict1
print(dict1.shape) # ❌ AttributeError: 'dict' object has no attribute 'shape'

In [58]:
df_dict1
print(df_dict1.shape) # (3, 3)

(3, 3)

### 6. DataFrame 컬럼 데이터 생성 및 구성

In [3]:
import pandas as pd

In [6]:
titanic_df = pd.read_csv('data/titanic/train.csv')
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [13]:
# 기억하면 좋은 잘쓰는 것 🌟
print(titanic_df.head()) # 상위 5개
print('*'*100)
print(titanic_df.tail()) # 하위 5개
print('*'*100)
print(titanic_df.info()) # 기본 정보
print('*'*100)
print(titanic_df.describe()) # 수치 정보

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S
****************************************************************************************************
     PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas
887          888         1       1              Graham, Miss. Margaret Edith
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"
889          890         1       1                     Behr, Mr. Karl Howell
890          891         0       3                       Dooley, Mr. Patrick

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked
886    male  27.0      0      0      211536  13.00   NaN        S
887  female  19.0      0      0      112053  30.00   B42        S
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S
889    male  26.0      0      0      111369  30.00  C148        C
890    male  32.0      0      0      370376   7.75   NaN        Q
****************************************************************************************************
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None
****************************************************************************************************
       PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000
mean    446.000000    0.383838    2.308642   29.699118    0.523008
std     257.353842    0.486592    0.836071   14.526497    1.102743
min       1.000000    0.000000    1.000000    0.420000    0.000000
25%     223.500000    0.000000    2.000000   20.125000    0.000000
50%     446.000000    0.000000    3.000000   28.000000    0.000000
75%     668.500000    1.000000    3.000000   38.000000    1.000000
max     891.000000    1.000000    3.000000   80.000000    8.000000

            Parch        Fare
count  891.000000  891.000000
mean     0.381594   32.204208
std      0.806057   49.693429
min      0.000000    0.000000
25%      0.000000    7.910400
50%      0.000000   14.454200
75%      0.000000   31.000000
max      6.000000  512.329200

In [17]:
# Age_0 컬럼 추가
# titanic_df.info()
titanic_df['Age_0'] = 1 # 컬럼 🅾️ 값 수정, 컬럼 ❌ 컬럼 추가
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
 12  Age_0        891 non-null    int64
dtypes: float64(2), int64(6), object(5)
memory usage: 90.6+ KB

In [24]:
# Age_by_10 컬럼 추가, Age*10
titanic_df['Age_by_10'] = titanic_df['Age']*10
titanic_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0,Age_by_10
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1,220.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1,380.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1,260.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1,350.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1,350.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,1,270.0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,1,190.0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,1,NaN
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,1,260.0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,1,320.0

In [25]:
# 일부 컬럼 조회
titanic_df['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [28]:
# 여러개의 컬럼 조회
titanic_df[['Age', 'Age_0', 'Age_by_10']].head()

    Age  Age_0  Age_by_10
0  22.0      1      220.0
1  38.0      1      380.0
2  26.0      1      260.0
3  35.0      1      350.0
4  35.0      1      350.0

In [ ]:
# Family_no 컬럼 추가 값 sibSp + Parch +1
titanic_df['Family_no'] = titanic_df['SibSp'] + titanic_df['Parch'] +1
titanic_df.info()
titanic_df.head()

### 7. DataFrame 데이터 삭제

In [40]:
# Age_0 컬럼 삭제
td_drop = titanic_df.drop('Age_0', axis = 1) # 기본값이 axis=0이 라서 행에서 컬럼을 찾음 KeyError: "['Age_0'] not found in axis"

In [ ]:
titanic_df.head() # Age_0 🅾️
td_drop.head() # Age_0 ❌

In [44]:
# 원본 삭제 후 반영
titanic_df.drop(['Age_by_10', 'Family_no'], axis=1, inplace=True)
titanic_df.head() # Age_0 ❌

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
titanic_df.drop([0, 1, 2], inplace=True) # 인덱스 행 기준 0번째 삭제

In [50]:
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S