# DataFrame Index

## Index란?
- Pandas의 Index는 데이터프레임과 시리즈의 각 행(row)를 고유하게 식별하는 역할을 수행함
- 관계형 데이베이스의 PK와 사한 개념
- 특징
    - 데이터 식별 역할 수행
    - 숫자, 문자열도 가능
    - 생성 후 직접 수정 불가
    - reset_index() 함수를 이용해서 재생성 가능

In [1]:
import warnings
warnings.filterwarnings(action='ignore')

import pandas as pd
import numpy as np

### 1. 인덱스 객체

In [5]:
# titanic DataSet Load
titanic_df = pd.read_csv('data/titanic/train.csv')
titanic_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
# Index 객체 추출
titanic_index = titanic_df.index
titanic_index.shape
titanic_index.values

In [13]:
print(titanic_index)
print(titanic_index.values.shape)
print(titanic_index.shape)

RangeIndex(start=0, stop=891, step=1)
(891,)
(891,)

In [14]:
# 생성된 Index 객체는 수정이 불가, Index는 수정이 안되는 불변 객체

## 2. Index 기반 연산 방식
- 🌟판다스는 인덱스 이름을 기준으로 데이터 맞춘 후 연산함

### (2) 기본 Series 생성 및 연산

In [17]:
# Series 생성
s1 = pd.Series([10,20,30])
s2 = pd.Series([40,50,60])
print(s1 + s2)
print(s1 - s2)
print(s1 * s2)
print(s1 / s2)

0    50
1    70
2    90
dtype: int64
0   -30
1   -30
2   -30
dtype: int64
0     400
1    1000
2    1800
dtype: int64
0    0.25
1    0.40
2    0.50
dtype: float64

In [22]:
#인덱스 지정
s1 = pd.Series([10,20,30], index=['a', 'b', 'c'])
s2 = pd.Series([40,50,60], index=['b', 'c', 'd'])

In [23]:
print(s1 + s2)
print(s1 - s2)
print(s1 * s2)
print(s1 / s2)

a     NaN
b    60.0
c    80.0
d     NaN
dtype: float64
a     NaN
b   -20.0
c   -20.0
d     NaN
dtype: float64
a       NaN
b     800.0
c    1500.0
d       NaN
dtype: float64
a    NaN
b    0.5
c    0.6
d    NaN
dtype: float64

### (2) 데이터 프레임 연산
- 🌟 동일한 인덱스, 동일한 컬럼명 기준으로 연산이 진행됨

In [32]:
df1 = pd.DataFrame(
    {
    'col1': [10, 20, 30],
    'col2': [40, 50, 60]
    }, index = ['a', 'b', 'c']
)
df2 = pd.DataFrame(
    {
    'col1': [10, 20, 30],
    'col3': [40, 50, 60]
    }, index = ['a', 'b', 'c']
)

In [37]:
print(df1)
print('-'*30)
print(df2)
print('-'*30)
df1 + df2 # 인덱스 컬럼명이 일치해야 연산이 수행됨

   col1  col2
a    10    40
b    20    50
c    30    60
------------------------------
   col1  col3
a    10    40
b    20    50
c    30    60
------------------------------

   col1  col2  col3
a    20   NaN   NaN
b    40   NaN   NaN
c    60   NaN   NaN

In [39]:
# df1객체에 'col3' 컬럼 추가
df1['col3'] = [20, 30, 40]
df1 + df2

   col1  col2  col3
a    20   NaN    60
b    40   NaN    80
c    60   NaN   100

## 3. reset_index()
- 실행 시 기존 index는 첫번째 컬럼으로 이동하고, 새로운 숫자의 index가 생성됨

In [42]:
# 데이터셋 확인
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [45]:
# 인덱스 재생성
td_reset_df = titanic_df.reset_index(inplace=False)

In [47]:
td_reset_df2 = td_reset_df.reset_index(inplace=False)
td_reset_df2

,level_0,index,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,4,4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,886,886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,887,887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,888,888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,889,889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,890,890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [48]:
td_reset_df2.drop('level_0', axis=1, inplace=True)

In [49]:
td_reset_df2.head()

,index,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [50]:
td_reset_df2.drop([0, 1, 2], inplace=True)
td_reset_df2.head()

,index,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S

In [51]:
# td_reset_df2의 인덱스 재생성, 원본반영
td_reset_df2.reset_index(inplace = True)
td_reset_df2.head()

,level_0,index,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
1,4,4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
2,5,5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
3,6,6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
4,7,7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S

In [53]:
td_reset_df2.drop(['level_0', 'index'], axis=1, inplace=True)
td_reset_df2.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
1,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
2,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
3,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
4,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S

## 4. rename() - 컬럼명, 인덱스명 변경
- 문법
    DF.rename(columns={'before':'after'})

In [54]:
titanic_df['Age_0'] = 0
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0

In [55]:
titanic_df['Age_0'] = 1
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1

In [61]:
titanic_df.rename(columns={'Age_0':'Age_1'}, inplace=True)
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_1
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1

In [65]:
# 인덱스 0, 2, 4 > 'a', 'b', 'c'
td_rename = titanic_df.rename(index={0:'a',2:'b', 4:'c'})
td_rename.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_1
a,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1
b,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1
c,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1

In [66]:
td_rename_index = td_rename.index
td_rename_index # 문자와 숫자가 섞여있음

Index(['a',   1, 'b',   3, 'c',   5,   6,   7,   8,   9,
       ...
       881, 882, 883, 884, 885, 886, 887, 888, 889, 890],
      dtype='object', length=891)