# 판다스 실습

In [3]:
import warnings
warnings.filterwarnings(action='ignore')

import pandas as pd
import numpy as np

In [8]:
### 1. 실습 데이터 준비
df = pd.read_csv('data/CARD_SUBWAY_MONTH_202605.csv', index_col=False) # 인덱스 만들어서 사용
df.head()

       사용일자  노선명   역명  승차총승객수  하차총승객수      등록일자
0  20260501  5호선   방이    5527    5357  20260504
1  20260501  5호선  둔촌동   10441    9979  20260504
2  20260501  5호선  상일동   10541    9932  20260504
3  20260501  5호선   고덕    7456    7257  20260504
4  20260501  5호선   명일    6377    6251  20260504

## 2. 데이터 탐색

In [10]:
# 상위 5개의 데이터 탐색
df.head()

       사용일자  노선명   역명  승차총승객수  하차총승객수      등록일자
0  20260501  5호선   방이    5527    5357  20260504
1  20260501  5호선  둔촌동   10441    9979  20260504
2  20260501  5호선  상일동   10541    9932  20260504
3  20260501  5호선   고덕    7456    7257  20260504
4  20260501  5호선   명일    6377    6251  20260504

In [11]:
# 데이터프레임의 형태 확인
df.shape

(19131, 6)

In [12]:
# 하위 데이터 10개를 조회
df.tail(10)

           사용일자  노선명                역명  승차총승객수  하차총승객수      등록일자
19121  20260531  8호선                문정    7350    7431  20260603
19122  20260531  8호선                장지   10401    9980  20260603
19123  20260531  8호선                복정    5988    5340  20260603
19124  20260531  8호선                산성    3611    3915  20260603
19125  20260531  8호선  남한산성입구(성남법원.검찰청)    6905    6413  20260603
19126  20260531  8호선             단대오거리    6782    6559  20260603
19127  20260531  8호선                신흥    3732    3895  20260603
19128  20260531  8호선                수진    4223    3812  20260603
19129  20260531  8호선                모란    3406    2806  20260603
19130  20260531  8호선               남위례    4515    4530  20260603

In [14]:
# 데이터의 사분위수, 표준편차, 분산 등 통계지표 조회
df.describe()

               사용일자         승차총승객수         하차총승객수          등록일자
count  1.913100e+04   19131.000000   19131.000000  1.913100e+04
mean   2.026052e+07   11811.350740   11759.563640  2.026053e+07
std    8.944833e+00   11836.994181   12011.261965  2.614125e+01
min    2.026050e+07       1.000000       0.000000  2.026050e+07
25%    2.026051e+07    4125.000000    4022.000000  2.026051e+07
50%    2.026052e+07    8396.000000    8135.000000  2.026052e+07
75%    2.026052e+07   15701.500000   15507.500000  2.026053e+07
max    2.026053e+07  101927.000000  115875.000000  2.026060e+07

In [32]:
# 데이터의 데이터 타입, 갯수 조회
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19131 entries, 0 to 19130
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   사용일자    19131 non-null  int64
 1   노선명     19131 non-null  object
 2   역명      19131 non-null  object
 3   승차총승객수  19131 non-null  int64
 4   하차총승객수  19131 non-null  int64
 5   등록일자    19131 non-null  int64
dtypes: int64(4), object(2)
memory usage: 896.9+ KB

In [40]:
df['노선명'].nunique() # 27
df['노선명'].unique() # 27

array(['5호선', '4호선', '경의선', '3호선', '2호선', '1호선', '경인선', '경춘선', '공항철도 1호선',
       '안산선', '과천선', '분당선', '서해선', '수인선', '신림선', '우이신설선', '일산선', '장항선',
       '중앙선', '경원선', '경부선', '경강선', '9호선2~3단계', '9호선', '8호선', '7호선', '6호선'],
      dtype=object)

In [41]:
df['역명'].nunique() # 27
df['역명'].unique() # 27

array(['방이', '둔촌동', '상일동', '고덕', '명일', '굽은다리(강동구민회관앞)', '길동', '강동',
       '천호(풍납토성)', '광나루(장신대)', '아차산(어린이대공원후문)', '군자(능동)', '장한평', '답십리',
       '마장', '왕십리(성동구청)', '행당', '신금호', '청구', '동대문역사문화공원(DDP)', '을지로4가',
       '종로3가', '광화문(세종문화회관)', '서대문', '충정로(경기대입구)', '애오개', '공덕', '마포',
       '여의나루', '여의도', '신길', '영등포시장', '영등포구청', '양평', '오목교(목동운동장앞)', '목동',
       '신정(은행정)', '까치산', '화곡', '우장산', '발산', '마곡', '송정', '김포공항', '개화산',
       '방화', '남태령', '사당', '총신대입구(이수)', '동작(현충원)', '이촌(국립중앙박물관)', '신용산',
       '삼각지(전쟁기념관)', '숙대입구(갈월)', '서울역', '회현(남대문시장)', '명동', '충무로', '동대문',
       '혜화', '한성대입구(삼선교)', '성신여대입구(돈암)', '길음', '미아사거리', '미아(서울사이버대학)',
       '수유(강북구청)', '쌍문', '창동', '노원', '상계', '한국항공대', '불암산', '오금', '경찰병원',
       '가락시장', '수서', '일원', '대청', '학여울', '대치', '도곡', '매봉', '양재(서초구청)',
       '남부터미널(예술의전당)', '교대(법원.검찰청)', '고속터미널', '잠원', '신사', '압구정', '옥수',
       '금호', '약수', '동대입구', '을지로3가', '안국', '경복궁(정부서울청사)', '독립문', '무악재',
       '홍제', '녹번', '불광', '연신내', '구파발', '지축', '용두(동대문구청)', '신정네거리', '양천구청',
       '도림천', '신설동', '신답', '용답', '아현', '이대', '신촌', '홍대입구', '합정', '당산',
       '문래', '신도림', '대림(구로구청)', '구로디지털단지', '신대방', '신림', '봉천',
       '서울대입구(관악구청)', '낙성대(강감찬)', '방배', '서초', '강남', '역삼', '선릉',
       '삼성(무역센터)', '종합운동장', '잠실새내', '잠실(송파구청)', '잠실나루', '강변(동서울터미널)',
       '구의(광진구청)', '건대입구', '성수', '뚝섬', '한양대', '상왕십리', '신당', '을지로입구', '시청',
       '동묘앞', '청량리(서울시립대입구)', '제기동', '종로5가', '종각', '강매', '행신', '능곡', '곡산',
       '백마', '풍산', '일산', '탄현', '야당', '운정', '금릉', '금촌', '월롱', '파주', '문산',
       '임진강', '운천', '개봉', '오류동', '역곡', '부천', '송내', '부평', '백운', '동암', '주안',
       '제물포', '동인천', '인천', '구일', '소사', '부개', '간석', '도원', '온수(성공회대입구)',
       '중동', '도화', '신내', '갈매', '별내', '퇴계원', '사릉', '금곡', '평내호평', '천마산',
       '마석', '대성리', '청평', '상천', '가평', '굴봉산', '백양리', '강촌', '김유정', '남춘천',
       '춘천', '디지털미디어시티', '산본', '마곡나루(서울식물원)', '계양', '검암', '청라국제도시', '운서',
       '공항화물청사', '인천공항1터미널', '인천공항2터미널', '영종', '선바위', '경마공원', '대공원', '과천',
       '정부과천청사', '인덕원', '평촌', '범계', '한티', '구룡', '개포동', '대모산입구', '수원',
       '서울숲', '압구정로데오', '강남구청', '선정릉', '가천대', '태평', '모란', '야탑', '서현',
       '수내', '정자', '미금', '오리', '이매', '보정', '죽전', '구성', '신갈', '기흥', '상갈',
       '청명', '영통', '망포', '매탄권선', '수원시청', '매교', '원종', '부천종합운동장', '고색',
       '오목천', '어천', '야목', '사리', '달월', '월곶', '소래포구', '인천논현', '호구포',
       '남동인더스파크', '원인재', '연수', '송도', '인하대', '숭의', '신포', '샛강', '대방',
       '서울지방병무청', '보라매', '보라매공원', '보라매병원', '당곡', '서원', '서울대벤처타운',
       '관악산(서울대)', '대야미', '반월', '상록수', '한대앞', '중앙', '고잔', '초지', '안산',
       '신길온천', '정왕', '오이도', '수리산', '북한산우이', '솔밭공원', '4.19민주묘지', '가오리',
       '화계', '삼양', '삼양사거리', '솔샘', '북한산보국문', '정릉', '보문', '원흥', '삼송', '원당',
       '화정', '대곡', '백석', '마두', '정발산', '주엽', '대화', '봉명', '쌍용(나사렛대)', '아산',
       '탕정', '배방', '온양온천', '신창(순천향대)', '회기', '중랑', '상봉', '망우', '양원', '구리',
       '도농', '양정', '덕소', '도심', '팔당', '운길산', '양수', '신원', '국수', '아신', '오빈',
       '원덕', '용문', '지평', '수색', '가좌', '서강대', '효창공원앞', '연천', '전곡', '청산',
       '소요산', '동두천', '보산', '동두천중앙', '지행', '덕정', '덕계', '양주', '녹양', '가능',
       '의정부', '회룡', '망월사', '도봉산', '도봉', '방학', '녹천', '월계', '광운대', '석계',
       '신이문', '외대앞', '응봉', '한남', '서빙고', '광명', '서동탄', '당정', '천안', '두정',
       '직산', '성환', '평택', '평택지제', '서정리', '송탄', '진위', '오산', '오산대', '세마',
       '병점', '세류', '독산', '화서', '성균관대', '의왕', '군포', '금정', '명학', '안양', '관악',
       '석수', '금천구청', '가산디지털단지', '구로', '영등포', '노량진', '용산', '남영', '성남',
       '여주', '세종대왕릉', '부발', '이천', '신둔도예촌', '곤지암', '초월', '경기광주', '삼동',
       '판교', '중앙보훈병원', '둔촌오륜', '올림픽공원(한국체대)', '한성백제', '송파나루', '석촌',
       '석촌고분', '삼전', '봉은사', '삼성중앙', '언주', '신논현', '사평', '신반포', '구반포',
       '흑석(중앙대입구)', '노들', '국회의사당', '선유도', '신목동', '염창', '등촌', '증미', '가양',
       '양천향교', '신방화', '공항시장', '개화', '남위례', '수진', '신흥', '단대오거리',
       '남한산성입구(성남법원.검찰청)', '산성', '복정', '장지', '문정', '송파', '몽촌토성(평화의문)',
       '강동구청', '암사', '암사역사공원', '천왕', '광명사거리', '철산', '남구로', '신풍', '신대방삼거리',
       '장승배기', '상도', '숭실대입구(살피재)', '남성', '이수', '내방', '반포', '논현', '학동',
       '청담', '자양(뚝섬한강공원)', '어린이대공원(세종대)', '중곡', '용마산(용마폭포공원)', '사가정',
       '면목', '중화', '먹골', '태릉입구', '공릉(서울과학기술대)', '하계', '중계', '마들', '수락산',
       '장암', '봉화산(서울의료원)', '화랑대(서울여대입구)', '돌곶이', '상월곡(한국과학기술연구원)',
       '월곡(동덕여대)', '고려대(종암)', '안암(고대병원앞)', '창신', '버티고개', '한강진', '이태원',
       '녹사평(용산구청)', '대흥(서강대앞)', '광흥창(서강)', '상수', '망원', '마포구청',
       '월드컵경기장(성산)', '증산(명지대앞)', '새절(신사)', '구산', '독바위', '역촌', '응암',
       '하남검단산', '하남시청(덕풍·신장)', '하남풍산', '미사', '강일', '마천', '거여', '개롱'],
      dtype=object)

In [42]:
# value_counts(): 몇번이나 반복(등장)하는가 확인
# 노선명 컬럼이 가지고 있는 데이터 분포 확인ㅁ
df['노선명'].value_counts()

노선명
5호선         1736
2호선         1550
7호선         1302
경부선         1209
6호선         1193
분당선         1080
3호선         1053
경원선         1021
경의선          843
4호선          806
9호선          775
중앙선          651
경인선          620
경춘선          589
8호선          589
수인선          558
공항철도 1호선     434
우이신설선        403
9호선2~3단계     403
안산선          403
경강선          372
신림선          341
일산선          332
1호선          310
과천선          248
장항선          217
서해선           93
Name: count, dtype: int64

## 3. 정렬

In [50]:
df.sort_values(by = ['승차총승객수'], ascending=False).head(10)

           사용일자  노선명        역명  승차총승객수  하차총승객수      등록일자
118    20260501  2호선      홍대입구  101927  115875  20260504
8668   20260515  2호선  잠실(송파구청)  100436   98646  20260518
682    20260502  2호선      홍대입구  100394  111108  20260505
8674   20260515  2호선        강남   98157   96835  20260518
13541  20260522  1호선       서울역   97514   98036  20260525
4342   20260508  2호선  잠실(송파구청)   97402   98062  20260511
17330  20260529  2호선        강남   96864   95651  20260601
13571  20260522  2호선        강남   96755   95209  20260525
4336   20260508  2호선        강남   96539   95218  20260511
8643   20260515  1호선       서울역   96164   95369  20260518

In [52]:
df.sort_values(by = ['하차총승객수'], ascending=False)[0:10]

           사용일자  노선명        역명  승차총승객수  하차총승객수      등록일자
118    20260501  2호선      홍대입구  101927  115875  20260504
682    20260502  2호선      홍대입구  100394  111108  20260505
9497   20260516  2호선      홍대입구   93826  105809  20260519
14108  20260523  2호선      홍대입구   93902  105501  20260526
1898   20260504  2호선      홍대입구   91747  101530  20260507
18406  20260530  2호선      홍대입구   90426  101159  20260602
5217   20260509  2호선      홍대입구   88321   99335  20260512
8668   20260515  2호선  잠실(송파구청)  100436   98646  20260518
4342   20260508  2호선  잠실(송파구청)   97402   98062  20260511
13541  20260522  1호선       서울역   97514   98036  20260525

## 4. 선택

In [61]:
# 사용일자 컬럼을 인덱스로 지정하여 df2 객체를 생성
df2 = df.set_index('사용일자')
df2

          노선명     역명  승차총승객수  하차총승객수      등록일자
사용일자
20260501  5호선     방이    5527    5357  20260504
20260501  5호선    둔촌동   10441    9979  20260504
20260501  5호선    상일동   10541    9932  20260504
20260501  5호선     고덕    7456    7257  20260504
20260501  5호선     명일    6377    6251  20260504
...       ...    ...     ...     ...       ...
20260531  8호선  단대오거리    6782    6559  20260603
20260531  8호선     신흥    3732    3895  20260603
20260531  8호선     수진    4223    3812  20260603
20260531  8호선     모란    3406    2806  20260603
20260531  8호선    남위례    4515    4530  20260603

[19131 rows x 5 columns]

In [63]:
print(df.head(3))
print('-'*100)
print(df2.head(3))

       사용일자  노선명   역명  승차총승객수  하차총승객수      등록일자
0  20260501  5호선   방이    5527    5357  20260504
1  20260501  5호선  둔촌동   10441    9979  20260504
2  20260501  5호선  상일동   10541    9932  20260504
----------------------------------------------------------------------------------------------------
          노선명   역명  승차총승객수  하차총승객수      등록일자
사용일자
20260501  5호선   방이    5527    5357  20260504
20260501  5호선  둔촌동   10441    9979  20260504
20260501  5호선  상일동   10541    9932  20260504

In [64]:
# 인덱스 검색 : loc/iloc
df2.iloc[1]

노선명            5호선
역명             둔촌동
승차총승객수       10441
하차총승객수        9979
등록일자      20260504
Name: 20260501, dtype: object

In [65]:
df2.loc[20260510]

          노선명    역명  승차총승객수  하차총승객수      등록일자
사용일자
20260510  7호선  태릉입구    6549    6519  20260513
20260510  5호선    신길    3197    3374  20260513
20260510  9호선  양천향교    5221    5473  20260513
20260510  9호선    가양   13415   13294  20260513
20260510  9호선    증미    3114    3300  20260513
...       ...   ...     ...     ...       ...
20260510  중앙선    양평    3155    2873  20260513
20260510  중앙선    원덕     479     373  20260513
20260510  중앙선    용문    4829    4286  20260513
20260510  중앙선    지평      63      70  20260513
20260510  2호선    방배    8554    8679  20260513

[617 rows x 5 columns]

In [70]:
# 불린 인덱싱
df2['노선명']=='2호선'

사용일자
20260501    False
20260501    False
20260501    False
20260501    False
20260501    False
            ...
20260531    False
20260531    False
20260531    False
20260531    False
20260531    False
Name: 노선명, Length: 19131, dtype: bool

In [71]:
# query
df2.query('노선명 == "2호선"')

          노선명         역명  승차총승객수  하차총승객수      등록일자
사용일자
20260501  2호선  용두(동대문구청)    1980    1746  20260504
20260501  2호선      신정네거리    7710    7364  20260504
20260501  2호선       양천구청    4845    4751  20260504
20260501  2호선        도림천     814     803  20260504
20260501  2호선        신설동    3984    3453  20260504
...       ...        ...     ...     ...       ...
20260531  2호선        신설동    3960    3664  20260603
20260531  2호선        도림천     910    1127  20260603
20260531  2호선       양천구청    3858    3948  20260603
20260531  2호선      신정네거리    6203    6115  20260603
20260531  2호선  용두(동대문구청)    1417    1393  20260603

[1550 rows x 5 columns]

In [76]:
df.query('승차총승객수 >= 50000')['역명']

86          고속터미널
118          홍대입구
134            강남
140      잠실(송파구청)
145            성수
           ...
18583          용산
18856         서울역
18881    잠실(송파구청)
18904        홍대입구
18936       고속터미널
Name: 역명, Length: 354, dtype: object

In [79]:
df[df['승차총승객수'] >=50000]['역명']

86          고속터미널
118          홍대입구
134            강남
140      잠실(송파구청)
145            성수
           ...
18583          용산
18856         서울역
18881    잠실(송파구청)
18904        홍대입구
18936       고속터미널
Name: 역명, Length: 354, dtype: object

In [81]:
df[(df['승차총승객수'] >=50000) & (df['역명'] == '강남')]

           사용일자  노선명  역명  승차총승객수  하차총승객수      등록일자
134    20260501  2호선  강남   56904   56781  20260504
698    20260502  2호선  강남   59964   58975  20260505
1857   20260504  2호선  강남   84694   83040  20260507
3204   20260506  2호선  강남   91795   89595  20260509
4202   20260507  2호선  강남   92886   90734  20260510
4336   20260508  2호선  강남   96539   95218  20260511
5175   20260509  2호선  강남   65373   64121  20260512
6204   20260511  2호선  강남   89081   87284  20260514
7275   20260512  2호선  강남   92102   89858  20260515
7777   20260513  2호선  강남   92470   90101  20260516
8354   20260514  2호선  강남   93239   90964  20260517
8674   20260515  2호선  강남   98157   96835  20260518
9480   20260516  2호선  강남   67653   66937  20260519
10526  20260518  2호선  강남   89110   87180  20260521
11650  20260519  2호선  강남   90261   88745  20260522
12287  20260520  2호선  강남   88401   85990  20260523
12467  20260521  2호선  강남   90794   88661  20260524
13571  20260522  2호선  강남   96755   95209  20260525
14091  20260523  2호선  강남   62833   62048  20260526
16033  20260526  2호선  강남   88118   86167  20260529
16602  20260527  2호선  강남   90633   88442  20260530
16836  20260528  2호선  강남   93004   90870  20260531
17330  20260529  2호선  강남   96864   95651  20260601
18423  20260530  2호선  강남   66323   65207  20260602

In [82]:
df.query('승차총승객수 >= 50000 & 역명 == "강남"')

           사용일자  노선명  역명  승차총승객수  하차총승객수      등록일자
134    20260501  2호선  강남   56904   56781  20260504
698    20260502  2호선  강남   59964   58975  20260505
1857   20260504  2호선  강남   84694   83040  20260507
3204   20260506  2호선  강남   91795   89595  20260509
4202   20260507  2호선  강남   92886   90734  20260510
4336   20260508  2호선  강남   96539   95218  20260511
5175   20260509  2호선  강남   65373   64121  20260512
6204   20260511  2호선  강남   89081   87284  20260514
7275   20260512  2호선  강남   92102   89858  20260515
7777   20260513  2호선  강남   92470   90101  20260516
8354   20260514  2호선  강남   93239   90964  20260517
8674   20260515  2호선  강남   98157   96835  20260518
9480   20260516  2호선  강남   67653   66937  20260519
10526  20260518  2호선  강남   89110   87180  20260521
11650  20260519  2호선  강남   90261   88745  20260522
12287  20260520  2호선  강남   88401   85990  20260523
12467  20260521  2호선  강남   90794   88661  20260524
13571  20260522  2호선  강남   96755   95209  20260525
14091  20260523  2호선  강남   62833   62048  20260526
16033  20260526  2호선  강남   88118   86167  20260529
16602  20260527  2호선  강남   90633   88442  20260530
16836  20260528  2호선  강남   93004   90870  20260531
17330  20260529  2호선  강남   96864   95651  20260601
18423  20260530  2호선  강남   66323   65207  20260602

In [85]:
df.agg(
    {
        '승차총승객수':'max',
        '하차총승객수':'min'
    }
)

승차총승객수    101927
하차총승객수         0
dtype: int64

In [87]:
df[['승차총승객수', '하차총승객수']].max()

승차총승객수    101927
하차총승객수    115875
dtype: int64

## 5. 삭제

In [92]:
# 행기준으로 삭제 0번지 행 삭제
df.drop(0)
# 행기준으로 삭제 3, 5, 7번지 행 삭제
df.drop([3, 5, 7])

           사용일자  노선명     역명  승차총승객수  하차총승객수      등록일자
0      20260501  5호선     방이    5527    5357  20260504
1      20260501  5호선    둔촌동   10441    9979  20260504
2      20260501  5호선    상일동   10541    9932  20260504
4      20260501  5호선     명일    6377    6251  20260504
6      20260501  5호선     길동    7758    7877  20260504
...         ...  ...    ...     ...     ...       ...
19126  20260531  8호선  단대오거리    6782    6559  20260603
19127  20260531  8호선     신흥    3732    3895  20260603
19128  20260531  8호선     수진    4223    3812  20260603
19129  20260531  8호선     모란    3406    2806  20260603
19130  20260531  8호선    남위례    4515    4530  20260603

[19128 rows x 6 columns]

In [94]:
df.drop(columns = '등록일자')

           사용일자  노선명     역명  승차총승객수  하차총승객수
0      20260501  5호선     방이    5527    5357
1      20260501  5호선    둔촌동   10441    9979
2      20260501  5호선    상일동   10541    9932
3      20260501  5호선     고덕    7456    7257
4      20260501  5호선     명일    6377    6251
...         ...  ...    ...     ...     ...
19126  20260531  8호선  단대오거리    6782    6559
19127  20260531  8호선     신흥    3732    3895
19128  20260531  8호선     수진    4223    3812
19129  20260531  8호선     모란    3406    2806
19130  20260531  8호선    남위례    4515    4530

[19131 rows x 5 columns]

In [95]:
df.drop(columns = ['등록일자', '역명'])

           사용일자  노선명  승차총승객수  하차총승객수
0      20260501  5호선    5527    5357
1      20260501  5호선   10441    9979
2      20260501  5호선   10541    9932
3      20260501  5호선    7456    7257
4      20260501  5호선    6377    6251
...         ...  ...     ...     ...
19126  20260531  8호선    6782    6559
19127  20260531  8호선    3732    3895
19128  20260531  8호선    4223    3812
19129  20260531  8호선    3406    2806
19130  20260531  8호선    4515    4530

[19131 rows x 4 columns]

## 6. 연산

In [97]:
df['승차총승객수_10'] = df['승차총승객수'] + 10
df

           사용일자  노선명     역명  승차총승객수  하차총승객수      등록일자  승차총승객수_10
0      20260501  5호선     방이    5527    5357  20260504       5537
1      20260501  5호선    둔촌동   10441    9979  20260504      10451
2      20260501  5호선    상일동   10541    9932  20260504      10551
3      20260501  5호선     고덕    7456    7257  20260504       7466
4      20260501  5호선     명일    6377    6251  20260504       6387
...         ...  ...    ...     ...     ...       ...        ...
19126  20260531  8호선  단대오거리    6782    6559  20260603       6792
19127  20260531  8호선     신흥    3732    3895  20260603       3742
19128  20260531  8호선     수진    4223    3812  20260603       4233
19129  20260531  8호선     모란    3406    2806  20260603       3416
19130  20260531  8호선    남위례    4515    4530  20260603       4525

[19131 rows x 7 columns]

In [99]:
df['승하차총승객수'] = df['승차총승객수'] - df['하차총승객수']
df

           사용일자  노선명     역명  승차총승객수  하차총승객수      등록일자  승차총승객수_10  승하차총승객수
0      20260501  5호선     방이    5527    5357  20260504       5537      170
1      20260501  5호선    둔촌동   10441    9979  20260504      10451      462
2      20260501  5호선    상일동   10541    9932  20260504      10551      609
3      20260501  5호선     고덕    7456    7257  20260504       7466      199
4      20260501  5호선     명일    6377    6251  20260504       6387      126
...         ...  ...    ...     ...     ...       ...        ...      ...
19126  20260531  8호선  단대오거리    6782    6559  20260603       6792      223
19127  20260531  8호선     신흥    3732    3895  20260603       3742     -163
19128  20260531  8호선     수진    4223    3812  20260603       4233      411
19129  20260531  8호선     모란    3406    2806  20260603       3416      600
19130  20260531  8호선    남위례    4515    4530  20260603       4525      -15

[19131 rows x 8 columns]

In [113]:
print(df['승하차총승객수'].mean())
print(df['승하차총승객수'].median())
print(df['승하차총승객수'].agg(['mean', 'median']))

51.78709947206105
97.0
mean      51.787099
median    97.000000
Name: 승하차총승객수, dtype: float64

In [ ]:
df['승하차총승객수합계'] = df['승차총승객수'] + df['하차총승객수']
df

In [122]:
print(df['승하차총승객수합계'].agg(['mean', 'median']))

mean      23570.91438
median    16489.00000
Name: 승하차총승객수합계, dtype: float64

In [124]:
# 인덱스 재생성 후 df2에 반영, 기존 인덱스 컬럼 유지
df2.reset_index(inplace = True)

In [125]:
df2.head()

       사용일자  노선명   역명  승차총승객수  하차총승객수      등록일자
0  20260501  5호선   방이    5527    5357  20260504
1  20260501  5호선  둔촌동   10441    9979  20260504
2  20260501  5호선  상일동   10541    9932  20260504
3  20260501  5호선   고덕    7456    7257  20260504
4  20260501  5호선   명일    6377    6251  20260504

In [127]:
df2_rail2 = df2.query('노선명 == "2호선"')
df2_rail2

           사용일자  노선명         역명  승차총승객수  하차총승객수      등록일자
107    20260501  2호선  용두(동대문구청)    1980    1746  20260504
108    20260501  2호선      신정네거리    7710    7364  20260504
109    20260501  2호선       양천구청    4845    4751  20260504
110    20260501  2호선        도림천     814     803  20260504
111    20260501  2호선        신설동    3984    3453  20260504
...         ...  ...        ...     ...     ...       ...
18911  20260531  2호선        신설동    3960    3664  20260603
18912  20260531  2호선        도림천     910    1127  20260603
18913  20260531  2호선       양천구청    3858    3948  20260603
18914  20260531  2호선      신정네거리    6203    6115  20260603
18915  20260531  2호선  용두(동대문구청)    1417    1393  20260603

[1550 rows x 6 columns]

In [130]:
df2_rail2_gn = df2.query('노선명 == "2호선" & 역명 == "강남"')
df2_rail2_gn.head()

          사용일자  노선명  역명  승차총승객수  하차총승객수      등록일자
134   20260501  2호선  강남   56904   56781  20260504
698   20260502  2호선  강남   59964   58975  20260505
1570  20260503  2호선  강남   38314   36857  20260506
1857  20260504  2호선  강남   84694   83040  20260507
2767  20260505  2호선  강남   40017   39003  20260508

In [133]:
df2_rail2['승하차총승객수'] = df2_rail2['승차총승객수'] - df2_rail2['하차총승객수']
df2_rail2

           사용일자  노선명         역명  승차총승객수  하차총승객수      등록일자  승하차총승객수
107    20260501  2호선  용두(동대문구청)    1980    1746  20260504      234
108    20260501  2호선      신정네거리    7710    7364  20260504      346
109    20260501  2호선       양천구청    4845    4751  20260504       94
110    20260501  2호선        도림천     814     803  20260504       11
111    20260501  2호선        신설동    3984    3453  20260504      531
...         ...  ...        ...     ...     ...       ...      ...
18911  20260531  2호선        신설동    3960    3664  20260603      296
18912  20260531  2호선        도림천     910    1127  20260603     -217
18913  20260531  2호선       양천구청    3858    3948  20260603      -90
18914  20260531  2호선      신정네거리    6203    6115  20260603       88
18915  20260531  2호선  용두(동대문구청)    1417    1393  20260603       24

[1550 rows x 7 columns]

In [ ]:
pd.merge(df2_rail2, df2_rail2_gn)

In [135]:
pd.merge(df2_rail2, df2_rail2_gn, how='left').head()

       사용일자  노선명         역명  승차총승객수  하차총승객수      등록일자  승하차총승객수
0  20260501  2호선  용두(동대문구청)    1980    1746  20260504      234
1  20260501  2호선      신정네거리    7710    7364  20260504      346
2  20260501  2호선       양천구청    4845    4751  20260504       94
3  20260501  2호선        도림천     814     803  20260504       11
4  20260501  2호선        신설동    3984    3453  20260504      531

## 7. 샘플링

In [137]:
df_sample_10 = df.sample(n=10)
df_sample_10

,사용일자,노선명,역명,승차총승객수,하차총승객수,등록일자,승차총승객수_10,승하차총승객수,승하차총승객수힙계,승하차총승객수합계
4840,20260508,경춘선,남춘천,4664,3650,20260511,4674,1014,8314,8314
9008,20260515,경원선,응봉,2450,1910,20260518,2460,540,4360,4360
5106,20260509,과천선,정부과천청사,8517,8151,20260512,8527,366,16668,16668
12740,20260521,7호선,태릉입구,12112,11850,20260524,12122,262,23962,23962
7065,20260512,경의선,운천,1,3,20260515,11,-2,4,4
14441,20260524,안산선,대야미,4496,3922,20260527,4506,574,8418,8418
5919,20260510,경원선,이촌(국립중앙박물관),3411,2777,20260513,3421,634,6188,6188
15674,20260526,분당선,강남구청,10950,12646,20260529,10960,-1696,23596,23596
6569,20260511,경춘선,대성리,549,378,20260514,559,171,927,927
4136,20260507,4호선,수유(강북구청),38748,39022,20260510,38758,-274,77770,77770

## 8. 그룹핑

In [141]:
print(df[['노선명', '사용일자', '사용일자']].value_counts)

<bound method DataFrame.value_counts of        노선명      사용일자      사용일자
0      5호선  20260501  20260501
1      5호선  20260501  20260501
2      5호선  20260501  20260501
3      5호선  20260501  20260501
4      5호선  20260501  20260501
...    ...       ...       ...
19126  8호선  20260531  20260531
19127  8호선  20260531  20260531
19128  8호선  20260531  20260531
19129  8호선  20260531  20260531
19130  8호선  20260531  20260531

[19131 rows x 3 columns]>

In [144]:
df.groupby(['사용일자', '노선명']).count()

                역명  승차총승객수  하차총승객수  등록일자  승차총승객수_10  승하차총승객수  승하차총승객수힙계  \
사용일자     노선명
20260501 1호선    10      10      10    10         10       10         10
         2호선    50      50      50    50         50       50         50
         3호선    34      34      34    34         34       34         34
         4호선    26      26      26    26         26       26         26
         5호선    56      56      56    56         56       56         56
...             ..     ...     ...   ...        ...      ...        ...
20260531 안산선    13      13      13    13         13       13         13
         우이신설선  13      13      13    13         13       13         13
         일산선    11      11      11    11         11       11         11
         장항선     7       7       7     7          7        7          7
         중앙선    21      21      21    21         21       21         21

                승하차총승객수합계
사용일자     노선명
20260501 1호선           10
         2호선           50
         3호선           34
         4호선           26
         5호선           56
...                   ...
20260531 안산선           13
         우이신설선         13
         일산선           11
         장항선            7
         중앙선           21

[837 rows x 8 columns]

## 9. 결측값(Nan)

In [145]:
df2['3호선'] = np.nan

In [146]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19131 entries, 0 to 19130
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   사용일자    19131 non-null  int64
 1   노선명     19131 non-null  object
 2   역명      19131 non-null  object
 3   승차총승객수  19131 non-null  int64
 4   하차총승객수  19131 non-null  int64
 5   등록일자    19131 non-null  int64
 6   3호선     0 non-null      float64
dtypes: float64(1), int64(4), object(2)
memory usage: 1.0+ MB

In [150]:
df2.isna().sum()
df2.isnull().sum()

사용일자          0
노선명           0
역명            0
승차총승객수        0
하차총승객수        0
등록일자          0
3호선       19131
dtype: int64

In [177]:
# 타이타닉 데이터셋 로드
td = pd.read_csv('data/titanic/train.csv')

In [178]:
td.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [179]:
td.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [180]:
td.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [181]:
# 결측치 대체
td['Age'] = td['Age'].fillna(td['Age'].mean())

In [182]:
td.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [183]:
td.drop(columns = 'Cabin', inplace = True)

In [186]:
td.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       2
dtype: int64

In [187]:
# Nan 값을 이전 값으로 대체
td['Embarked'] = td['Embarked'].ffill()

In [188]:
td.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64